# Default values for flask-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

flask:
  name: flask
  container:
     name: my-flask-app
     image: shubh228/flask-app:v1
     containerPort: 5000
     
  

service:
  type: NodePort
  port: 5000
  protocol: TCP
  name: flask-svc
