apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.flask.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.flask.name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.flask.name }}
    spec:
      containers:
      - name: {{ .Values.flask.container.name }}
        image: {{ .Values.flask.container.image }}
        ports:
        - containerPort: {{ .Values.flask.container.containerPort }}

