apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  ports:
   -  port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.flask.container.containerPort }}
  selector:
    app: {{ .Values.flask.name }}
  type: {{ .Values.service.type }}
